channels:
    - conda-forge
name:
    torch-em-dev
dependencies:
    - affogato
    - bioimageio.spec
    - bioimageio.core
    - imagecodecs
    - python-elf
    - pytorch
    - tensorboard
    - tifffile
    - torchvision
    - tqdm
    - kornia
