channels:
    - pytorch
    - conda-forge
name:
    torch-em-cpu
dependencies:
    - affogato
    - bioimageio.spec <0.5.0
    - bioimageio.core >=0.5.0
    - cpuonly
    - imagecodecs
    - python-elf
    - pytorch >=2.0
    - tensorboard
    - tifffile
    - torchvision
    - tqdm
    - kornia
