channels:
    - pytorch
    - conda-forge
name:
    torch-em-cpu
dependencies:
    - affogato
    - bioimageio.spec >=0.5.0
    - bioimageio.core >=0.6.0
    - cpuonly
    - imagecodecs
    - natsort
    # This pin is necessary because later nifty versions have import errors on windows.
    - nifty =1.2.1=*_4
    - protobuf <5
    - python-elf
    - pytorch >=2.0
    - tensorboard
    - tifffile
    - torchvision
    - tqdm
    - kornia
