channels:
    - conda-forge
name:
    torch-em-dev
dependencies:
    - affogato
    - bioimageio.spec
    - bioimageio.core
    - imagecodecs
    - natsort
    - nifty >= 1.2.3
    - python-elf
    - pytorch
    - tensorboard
    - tifffile >=2024
    - torchvision
    - tqdm
    - kornia
    - xarray <2025.3.0
