channels:
    - conda-forge
name:
    torch-em-dev
dependencies:
    - bioimage-cpp
    - bioimageio.spec
    - bioimageio.core >=0.8.0
    - imagecodecs
    - kornia
    - natsort
    - python-elf
    - pytorch
    - requests
    - tensorboard
    - tifffile >=2024
    - torchvision
    - tqdm
