name: test

on: [push, pull_request]

jobs:
  test-conda:
    name: conda ${{ matrix.os }} ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yaml
          create-args: >-
            python=${{ matrix.python-version }}

      - name: Install segment-anything
        shell: bash -l {0}
        run: micromamba install -c conda-forge segment-anything

      - name: Install package
        shell: bash -l {0}
        run: pip install --no-deps -e .

      - name: Run tests
        shell: bash -l {0}
        run: python -m unittest discover -s test -v

  test-pip:
    name: pip ${{ matrix.os }} ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: pip install -e .

      - name: Install segment-anything
        run: pip install segment-anything

      - name: Run tests
        run: python -m unittest discover -s test -v
